<?php

namespace HiEvents\Http\Request\AccessLog;

use HiEvents\Http\Request\BaseRequest;
use Illuminate\Validation\Rule;

class RecordAccessScanRequest extends BaseRequest
{
    public function rules(): array
    {
        return [
            'identifier' => ['required', 'string', 'max:255'],
            'access_point_id' => [
                'required',
                'integer',
                Rule::exists('access_points', 'id')->whereNull('deleted_at'),
            ],
            'direction' => ['nullable', 'string', 'in:ENTRY,EXIT'],
            'identifier_type' => ['nullable', 'string', 'in:QR,BARCODE,RFID,NFC,MANUAL'],

            // Generated by the device before the scan so a replayed offline queue is
            // idempotent rather than a second admission.
            'client_generated_id' => ['nullable', 'uuid'],

            // The device clock. Kept distinct from the server clock so a late offline
            // submission remains analysable.
            'occurred_at' => ['nullable', 'date'],
        ];
    }
}
