<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * The append-only access record.
     *
     * This supersedes rather than extends attendee_check_ins, which carries a UNIQUE
     * index on (attendee_id, check_in_list_id) and implements check-out as a
     * soft-delete. That shape forbids re-entry and destroys the history an access log
     * exists to preserve, so it cannot be evolved into one.
     *
     * Rows are never updated and never deleted. Denials are recorded too: a denied scan
     * is the most operationally interesting event, and logging only successes makes an
     * incident uninvestigable.
     *
     * @see docs/arzo-master-plan/24-access-control.md
     */
    public function up(): void
    {
        Schema::create('access_logs', function (Blueprint $table) {
            $table->id();
            $table->string('short_id', 32)->unique();
            $table->foreignId('event_id')->constrained('events')->cascadeOnDelete();
            $table->foreignId('access_point_id')->nullable()->constrained('access_points')->nullOnDelete();
            $table->foreignId('zone_id')->nullable()->constrained('zones')->nullOnDelete();
            $table->foreignId('attendee_id')->nullable()->constrained('attendees')->nullOnDelete();
            $table->foreignId('person_id')->nullable()->constrained('persons')->nullOnDelete();

            // Device clock when the scan happened, versus server clock when it arrived.
            // Offline devices submit late and their clocks drift; collapsing these into one
            // column loses the ability to analyse a replay.
            $table->timestampTz('occurred_at');
            $table->timestampTz('recorded_at')->useCurrent();

            $table->string('direction', 16)->default('ENTRY');
            $table->string('result', 48);
            $table->string('raw_identifier', 255)->nullable();
            $table->string('identifier_type', 16)->default('QR');
            $table->foreignId('operator_user_id')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('override_by')->nullable()->constrained('users')->nullOnDelete();
            $table->string('override_reason', 255)->nullable();

            // Generated by the device before the scan, so replaying a queued offline scan
            // is a no-op on conflict. This is what makes at-least-once delivery safe.
            $table->uuid('client_generated_id')->nullable()->unique();
            $table->boolean('is_offline_replay')->default(false);

            $table->string('source', 16)->default('SCAN');
            $table->ipAddress('ip_address')->nullable();
            $table->jsonb('metadata')->nullable();
            $table->timestamp('created_at')->useCurrent();

            $table->index(['event_id', 'occurred_at']);
            $table->index(['zone_id', 'occurred_at']);
            $table->index(['attendee_id', 'occurred_at']);
            $table->index('access_point_id');
        });

        Schema::create('session_registrations', function (Blueprint $table) {
            $table->id();
            $table->string('short_id', 32)->unique();
            $table->foreignId('session_id')->constrained('sessions')->cascadeOnDelete();
            $table->foreignId('attendee_id')->constrained('attendees')->cascadeOnDelete();
            $table->string('status', 32)->default('REGISTERED');
            $table->timestampTz('registered_at')->useCurrent();
            $table->timestampTz('cancelled_at')->nullable();
            $table->unsignedInteger('waitlist_position')->nullable();
            $table->jsonb('metadata')->nullable();
            $table->timestamps();
            $table->softDeletes();

            $table->index('session_id');
            $table->index('attendee_id');
            $table->index(['session_id', 'status']);
        });

        Schema::create('session_attendance', function (Blueprint $table) {
            $table->id();
            $table->string('short_id', 32)->unique();
            $table->foreignId('session_id')->constrained('sessions')->cascadeOnDelete();
            $table->foreignId('attendee_id')->constrained('attendees')->cascadeOnDelete();
            $table->timestampTz('scanned_at');
            $table->string('direction', 16)->default('IN');
            $table->foreignId('access_point_id')->nullable()->constrained('access_points')->nullOnDelete();
            $table->foreignId('recorded_by')->nullable()->constrained('users')->nullOnDelete();
            $table->string('source', 16)->default('SCAN');

            // Deliberately no unique constraint on (session_id, attendee_id): leaving and
            // returning must both be recordable. Idempotency comes from the client key.
            $table->uuid('client_generated_id')->nullable()->unique();

            $table->jsonb('metadata')->nullable();
            $table->timestamps();

            $table->index(['session_id', 'attendee_id', 'scanned_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('session_attendance');
        Schema::dropIfExists('session_registrations');
        Schema::dropIfExists('access_logs');
    }
};
